name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      #   - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Install dependencies for frontend
        working-directory: ./frontend
        run: npm ci
      - name: Check style for frontend
        working-directory: ./frontend
        run: npm run lint
      - name: Build for frontend
        working-directory: ./frontend
        run: npm run build
      - name: Test for frontend
        working-directory: ./frontend
        run: npm run test
