name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      #   - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Install dependencies for backend
        run: npm ci
      - name: Test backend
        run: npm run test:backend
      - name: Install dependencies for frontend
        run: npm run install:frontend
      - name: Check style for frontend
        run: npm run lint:frontend
      - name: Build for frontend
        run: npm run build:frontend
      - name: Test for frontend
        run: npm run test:frontend
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: e2e tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
